spring:
  application:
    name: notificaton
  r2dbc:
    url: r2dbc:postgresql://${DB_POSTGRES_HOST:172.17.0.2}:${DB_POSTGRES_PORT:5432}/${DB_POSTGRES_NAME:notification}
    username: ${DB_POSTGRES_USER:notification}
    password: ${DB_POSTGRES_PASSWORD:notification}
    pool:
      enabled: true
  sql:
    init:
      mode: always # always | embedded | never
springdoc:
  swagger-ui:
    path: /swagger-ui.html
